// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hello.proto

/*
Package proto is a generated protocol buffer package.

package rpc;      //错误的做法,错误的包

It is generated from these files:
	hello.proto

It has these top-level messages:
	UserRq
	UserRp
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

// 请求
type UserRq struct {
	Id int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *UserRq) Reset()                    { *m = UserRq{} }
func (m *UserRq) String() string            { return proto1.CompactTextString(m) }
func (*UserRq) ProtoMessage()               {}
func (*UserRq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UserRq) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

// 响应
type UserRp struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *UserRp) Reset()                    { *m = UserRp{} }
func (m *UserRp) String() string            { return proto1.CompactTextString(m) }
func (*UserRp) ProtoMessage()               {}
func (*UserRp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UserRp) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto1.RegisterType((*UserRq)(nil), "proto.UserRq")
	proto1.RegisterType((*UserRp)(nil), "proto.UserRp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Data service

type DataClient interface {
	GetUser(ctx context.Context, in *UserRq, opts ...grpc.CallOption) (*UserRp, error)
}

type dataClient struct {
	cc *grpc.ClientConn
}

func NewDataClient(cc *grpc.ClientConn) DataClient {
	return &dataClient{cc}
}

func (c *dataClient) GetUser(ctx context.Context, in *UserRq, opts ...grpc.CallOption) (*UserRp, error) {
	out := new(UserRp)
	err := grpc.Invoke(ctx, "/proto.Data/GetUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Data service

type DataServer interface {
	GetUser(context.Context, *UserRq) (*UserRp, error)
}

func RegisterDataServer(s *grpc.Server, srv DataServer) {
	s.RegisterService(&_Data_serviceDesc, srv)
}

func _Data_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Data/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServer).GetUser(ctx, req.(*UserRq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Data_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Data",
	HandlerType: (*DataServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _Data_GetUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hello.proto",
}

func init() { proto1.RegisterFile("hello.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 118 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0x48, 0xcd, 0xc9,
	0xc9, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x12, 0x5c, 0x6c, 0xa1,
	0xc5, 0xa9, 0x45, 0x41, 0x85, 0x42, 0x7c, 0x5c, 0x4c, 0x99, 0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a,
	0xac, 0x41, 0x4c, 0x99, 0x29, 0x4a, 0x32, 0x50, 0x99, 0x02, 0x21, 0x21, 0x2e, 0x96, 0xbc, 0xc4,
	0xdc, 0x54, 0xb0, 0x1c, 0x67, 0x10, 0x98, 0x6d, 0xa4, 0xcf, 0xc5, 0xe2, 0x92, 0x58, 0x92, 0x28,
	0xa4, 0xce, 0xc5, 0xee, 0x9e, 0x5a, 0x02, 0x52, 0x28, 0xc4, 0x0b, 0x31, 0x59, 0x0f, 0x62, 0x9e,
	0x14, 0x0a, 0xb7, 0x20, 0x89, 0x0d, 0xcc, 0x33, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xd3, 0x86,
	0x75, 0x05, 0x85, 0x00, 0x00, 0x00,
}
